# Generated by Django 4.2.8 on 2023-12-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('curse', models.CharField(max_length=256, verbose_name='Проклятье')),
                ('comment', models.CharField(max_length=512, null=True, verbose_name='Комментарий')),
                ('duration', models.IntegerField(verbose_name='Продолжительность проклятья')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('link', models.URLField(default=None, null=True, verbose_name='Ссылка на профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Проклятье',
                'verbose_name_plural': 'Проклятья',
            },
        ),
    ]
